### ISSUE TITLE
Issue When Analyzing any resource

### ISSUE THREAD

**Issue by ShoaibQureshi01** [feiskyer/kube-copilot#168]
### Discussed in https://github.com/feiskyer/kube-copilot/discussions/167

<div type='discussions-op-text'>

<sup>Originally posted by **ShoaibQureshi01** December 14, 2023</sup>
Hi there, 
i have installed the kube-copilot using helm with Azure OpenAI gpt-35-turbo-16k model. Now every other function is working fine except the analyze it is showing some python syntax error like this 

here's the screenshot of the error 
![image](https://github.com/feiskyer/kube-copilot/assets/122212466/54a14ff6-f97f-41e3-b73c-b92fac65cfca)

Got this in Logs of kube-copilot pod :- 
"""
root@master:~/service# kubectl logs kube-copilot-6ff7b996c9-f2wbt
  You can now view your Streamlit app in your browser.
  Network URL: http://172.16.194.186:8501
  External URL: 

> Entering new AgentExecutor chain...
Question: What is the YAML for Pod web in namespace default?
Thought: I can use the `kubectl` command to retrieve the YAML for the Pod.
Action:
```
{
  "action": "python",
  "action_input": "kubectl get -n default Pod web -o yaml"
}
```

Observation: SyntaxError('invalid syntax', ('<string>', 1, 9, 'kubectl get -n default Pod web -o yaml\n', 1, 12))
Thought:Could not parse LLM output: There seems to be a syntax error in the Python code. I need to fix the syntax error and try again.
Observation: There seems to be a syntax error in the Python code. I need to fix the syntax error and try again.
Thought:I need to fix the syntax error in the Python code and try again. The error is likely due to the fact that the command is not enclosed in quotes. I will enclose the command in quotes and try again.
"""

------------------------------------------------ ----------------------------------------

For reference here is the logs of diagnose function which is working fine 

""""
> Entering new AgentExecutor chain...
Question: What is the issue with Pod mypod in namespace default?
Thought: To diagnose the issue with the Pod, we need to retrieve information about its status, logs, and events using the Kubernetes Python SDK.
Action:
```
{
  "action": "python",
  "action_input": "from kubernetes import client, config\n\nconfig.load_kube_config()\nv1 = client.CoreV1Api()\n\n# Retrieve Pod status\npod_status = v1.read_namespaced_pod_status('mypod', 'default')\n\n# Retrieve Pod logs\npod_logs = v1.read_namespaced_pod_log('mypod', 'default')\n\n# Retrieve Pod events\npod_events = v1.list_namespaced_event('default', field_selector=f'involvedObject.name=mypod')\n\nprint(pod_status)\nprint(pod_logs)\nprint(pod_events)"
}
```
Observation: {'api_version': 'v1',
 'kind': 'Pod',
 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"httpd"},"name":"mypod","namespace":"default"},"spec":{"containers":[{"image":"httpd","name":"myhttpd","ports":[{"containerPort":80}]}],"nodeSelector":{"node":"mynode"}}}\n'},
              'creation_timestamp': datetime.datetime(2023, 12, 14, 6, 24, 3, tzinfo=tzlocal()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': {'app': 'httpd'},
              'managed_fields': [{'api_version': 'v1',
......Output Ommited

-----------------------------------------------------

From what i can think of is that the diagnose function is converting the prompt into python code but the analyze function is not, it is using the simple bash kubectl command. But i am not a developer and that is just a guess. 

Any reply would be of help. 
Thanks.           </div>

**Comment by feiskyer** [comment]
yes, I got similar behaviors on gpt-3 models as well. Please try GPT-4 models, which would generate much more reliable results.
