### ISSUE TITLE
GOOGLE_API key and CSE ID error while trying to install kube-copliot with Azure Open AI

### ISSUE THREAD

**Issue by dilipk8** [feiskyer/kube-copilot#33]
I am trying to setup kube-copilot using Azure Open AI.
I've set the OPENAI_API_TYPE, OPENAI_API_BASE and OPENAI_API_KEY.
Ran -
helm install kube-copilot kube-copilot --repo https://feisky.xyz/kube-copilot --set openai.apiModel=gpt-4 --set openai.apiKey=$OPENAI_API_KEY --set openai.apiBase=$OPENAI_API_BASE

Error message is - 
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Secret.data.GOOGLE_API_KEY, unknown object type "nil" in Secret.data.GOOGLE_CSE_ID]

**Comment by feiskyer** [comment]
@dilipk8 thanks for reporting the issue. Pushed a new release with quota added for secret values, could you try again?

**Comment by dilipk8** [comment]
Thanks @feiskyer  it works fine now.
